# Generated by Django 5.1.6 on 2025-02-28 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
                ('location', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('UPCOMING', 'upcoming'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=30)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.category')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('event', models.ManyToManyField(to='tasks.event')),
            ],
        ),
    ]
