# Generated by Django 5.1.6 on 2025-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='particiID', to='tasks.event'),
        ),
    ]
