# Generated by Django 5.1.6 on 2025-03-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='participants', to='tasks.event'),
        ),
    ]
