# Generated by Django 5.1.6 on 2025-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(blank=True, related_name='events_speaker', to='tasks.speaker'),
        ),
    ]
