# Generated by Django 5.1.6 on 2025-03-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ManyToManyField(related_name='participat', to='tasks.event'),
        ),
    ]
