# Generated by Django 5.1.6 on 2025-07-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_event_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(blank=True, to='tasks.speaker'),
        ),
    ]
