# Generated by Django 5.1.6 on 2025-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.speaker'),
        ),
    ]
