# Generated by Django 5.1.4 on 2025-07-12 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_event_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
